# Generated by Django 3.2.20 on 2023-07-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230717_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='track',
            field=models.CharField(blank=True, choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Design', 'Design')], max_length=20, verbose_name='track'),
        ),
    ]
