# Generated by Django 3.2.20 on 2023-08-03 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('regist_start_at', models.DateTimeField()),
                ('regist_end_at', models.DateTimeField()),
                ('activity_start_at', models.DateTimeField()),
                ('activity_end_at', models.DateTimeField()),
                ('is_registing', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('subscriber_limit', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ManyToManyField(related_name='program', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
